const GIGABYTE_IN_BYTES = 1024 ** 3;
export const REPOSITORY_SIZE_LIMIT = GIGABYTE_IN_BYTES * 2;
export const REPOSITORY_SOFT_SIZE_LIMIT = GIGABYTE_IN_BYTES;
export const CODE_INSIGHTS_REPORTS_PAGE_SIZE = 10;
export const CODE_INSIGHTS_ANNOTATIONS_PAGE_SIZE = 100;
